### ISSUE TITLE
Include HTML in alerts?

### ISSUE THREAD

**Issue by jamiesoncj** [asktomsk/bootstrap-alerts#10]
Is it possible to include HTML in an alert? I'd like to be able to do something like this:
```javascript
Alerts.add('Alert text here. You should take action on this by <a href="/fix-issue">clicking here</a>.');
```

Is it possible to do this? It doesn't seem to render as HTML.

**Comment by jamiesoncj** [comment]
Figured this out after looking at the code (I think it's missing from the README). For anyone else who is confused like me, you just need to add ```html: true``` to the options. E.g.
```javascript
Alerts.add('Alert text here. You should take action on this by <a href="/fix-issue">clicking here</a>.', {html: true});
```

Apologies for my ineptitude!

**Comment by asktomsk** [comment]
Try to put ````html: true```` in options.
This feature was added by @vonrussel in this commit: https://github.com/asktomsk/bootstrap-alerts/commit/b00a642673df6ce830be9b3ed6f7cbfcab24694f
But I didn't actually test it.
